# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'asd', '0001_initial'), (b'asd', '0002_model1_age'), (b'asd', '0003_remove_model1_age')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
