# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asd', '0001_squashed_0003_remove_model1_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='model1',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
