# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asd', '0002_model1_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model1',
            name='age',
        ),
    ]
